#!/bin/bash

cd "$HOME/nix-dotfiles" || exit

# Set the COLOR_SCHEME environment variable based on some condition
if [[ -n "$1" ]]; then
    export COLOR_SCHEME="$1"  # Use the first argument passed to the script
else
    export COLOR_SCHEME="catppuccin"  # Default value
fi

echo "Using color scheme: $COLOR_SCHEME"

nixos-rebuild switch --impure --flake . --use-remote-sudo
home-manager switch --impure --flake .?submodules=1

hyprctl dispatch restart

WALLPAPER_DIR="$HOME/nix-dotfiles/assets/images"
# Find the wallpaper file with the corresponding theme name
WALLPAPER_PATH=$(find "$WALLPAPER_DIR" -type f -name "$COLOR_SCHEME.*" | head -n 1)
# Preload the wallpaper
hyprctl hyprpaper preload "$WALLPAPER_PATH"
# Loop through each monitor and set the wallpaper
for monitor in $(hyprctl monitors | grep 'Monitor' | awk '{ print $2 }'); do
    hyprctl hyprpaper wallpaper "$monitor,$WALLPAPER_PATH"
done

ags -q
ags &

pkill kitty
kitty &
